updated ci_cd pipeline

diff --git a/.github/workflows/ci-cd-pipeline.yaml b/.github/workflows/ci-cd-pipeline.yaml
--- a/.github/workflows/ci-cd-pipeline.yaml
+++ b/.github/workflows/ci-cd-pipeline.yaml
@@ -71,11 +71,21 @@ jobs:
             --container-image-uri=gcr.io/cloud-aiplatform/prediction/sklearn-cpu.1-3:latest \
             --artifact-uri=gs://mlops-california-housing-bucket-1/models/model_deployment/
 
-          # Get the new Model ID
+          # Get the new Model ID with the --region flag and sort by creation time
           NEW_MODEL_ID=$(gcloud ai models list \
             --region=us-central1 \
-            --filter="display_name=California Housing Model Updated" \
+            --filter="display_name='California Housing Model Updated'" \
+            --sort-by=~create_time \
+            --limit=1 \
             --format="value(name)")
+        
+          echo "New Model ID: $NEW_MODEL_ID"
+        
+          # Check if NEW_MODEL_ID is not empty
+          if [ -z "$NEW_MODEL_ID" ]; then
+            echo "Error: NEW_MODEL_ID is empty. Model upload might have failed or the display name filter did not match any models."
+            exit 1
+          fi
 
           # Deploy the new model to the endpoint
           gcloud ai endpoints deploy-model \
